# Generated by Django 2.1 on 2018-08-18 00:44

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('birth_date', models.DateField()),
                ('last_education', models.CharField(choices=[('PRI', 'Primary'), ('INT', 'Intermediate'), ('HIG', 'High'), ('BAC', 'Bachelor Degree'), ('MAS', 'Master Degree'), ('PHD', 'Doctor Degree')], default='SMU', max_length=3, null=True)),
                ('join_date', models.DateTimeField(default=datetime.datetime.now)),
                ('reminder_time', models.TimeField()),
                ('email', models.EmailField(max_length=254, null=True)),
                ('website', models.URLField(null=True)),
                ('address', models.TextField(null=True)),
                ('member_type', models.CharField(choices=[('1', 'REGULAR'), ('2', 'GOLD'), ('3', 'PLATINUM')], default='REGULAR', max_length=20)),
                ('term_day', models.IntegerField(default=30)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('bio', ckeditor.fields.RichTextField(blank=True)),
            ],
            options={
                'db_table': 'tb_author',
            },
        ),
    ]
