# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-17 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('uid', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('is_male', models.BooleanField()),
                ('birth_date', models.DateField()),
                ('birth_time', models.TimeField()),
                ('registration_time', models.DateTimeField()),
                ('email', models.EmailField(max_length=254, null=True)),
                ('website', models.URLField(null=True)),
                ('address', models.TextField(null=True)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('last_education', models.CharField(choices=[('SD', 'Primary'), ('SMP', 'Intermediate'), ('SMU', 'High'), ('S1', 'Bachelor Degree'), ('S2', 'Master Degree'), ('S3', 'Doctor Degree')], default='SMU', max_length=3, null=True)),
                ('photo', models.BinaryField(null=True)),
            ],
            options={
                'db_table': 'tb_person',
            },
        ),
    ]
